# Generated by Django 5.1.2 on 2025-03-02 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file_type',
        ),
    ]
