# Generated by Django 5.1.2 on 2025-03-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata_app', '0002_rename_created_at_uploadedfile_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(max_length=255, upload_to='uploads/'),
        ),
    ]
